set(_CATKIN_CURRENT_PACKAGE "aue_finals")
set(aue_finals_VERSION "0.0.0")
set(aue_finals_MAINTAINER "administrator <administrator@todo.todo>")
set(aue_finals_PACKAGE_FORMAT "2")
set(aue_finals_BUILD_DEPENDS "cv_bridge" "rospy" "sensor_msgs" "std_msgs")
set(aue_finals_BUILD_EXPORT_DEPENDS "cv_bridge" "rospy" "sensor_msgs" "std_msgs")
set(aue_finals_BUILDTOOL_DEPENDS "catkin")
set(aue_finals_BUILDTOOL_EXPORT_DEPENDS )
set(aue_finals_EXEC_DEPENDS "cv_bridge" "rospy" "sensor_msgs" "std_msgs")
set(aue_finals_RUN_DEPENDS "cv_bridge" "rospy" "sensor_msgs" "std_msgs")
set(aue_finals_TEST_DEPENDS )
set(aue_finals_DOC_DEPENDS )
set(aue_finals_URL_WEBSITE "")
set(aue_finals_URL_BUGTRACKER "")
set(aue_finals_URL_REPOSITORY "")
set(aue_finals_DEPRECATED "")