#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/aue_finals:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/vision_opencv:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/turtlebot3_simulations:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/turtlebot3_gazebo:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/turtlebot3_fake:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/opencv_tests:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/apriltag_ros:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/image_geometry:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/assignment6_trackingandfollowing:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/cv_bridge:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/assignment5_wallfollowingandobstacleavoidance:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/assignment3_turtlebot3:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel:/opt/ros/noetic:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/apriltag:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/apriltag'
export LD_LIBRARY_PATH='/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/aue_finals/lib:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/turtlebot3_gazebo/lib:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/turtlebot3_fake/lib:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/opencv_tests/lib:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/apriltag_ros/lib:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/image_geometry/lib:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/assignment6_trackingandfollowing/lib:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/cv_bridge/lib:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/assignment5_wallfollowingandobstacleavoidance/lib:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/assignment3_turtlebot3/lib:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel/lib:/opt/ros/noetic/lib:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/apriltag/lib:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/apriltag/lib/x86_64-linux-gnu:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/apriltag/lib'
export PATH='/opt/ros/noetic/bin:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/apriltag/bin:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/apriltag/bin:/home/administrator/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export PKG_CONFIG_PATH='/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/aue_finals/lib/pkgconfig:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/turtlebot3_gazebo/lib/pkgconfig:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/turtlebot3_fake/lib/pkgconfig:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/opencv_tests/lib/pkgconfig:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/apriltag_ros/lib/pkgconfig:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/image_geometry/lib/pkgconfig:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/assignment6_trackingandfollowing/lib/pkgconfig:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/cv_bridge/lib/pkgconfig:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/assignment5_wallfollowingandobstacleavoidance/lib/pkgconfig:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/assignment3_turtlebot3/lib/pkgconfig:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel/lib/pkgconfig:/opt/ros/noetic/lib/pkgconfig:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/apriltag/lib/pkgconfig:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/apriltag/lib/x86_64-linux-gnu/pkgconfig:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/apriltag/lib/pkgconfig'
export PYTHONPATH='/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/apriltag_ros/lib/python3/dist-packages:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/image_geometry/lib/python3/dist-packages:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/cv_bridge/lib/python3/dist-packages:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel/lib/python3/dist-packages:/opt/ros/noetic/lib/python3/dist-packages:/home/administrator/git_ws/AuE893_SP21_KartikLoya/catkin_ws/devel_isolated/apriltag/lib/python3/dist-packages'